[mode]

if_tshark = 0
if_mitm = 1
if_vpn = 0

[chrome]

chrome_user_data_path = C:/Users/TwT/AppData/Local/Google/Chrome/SeleniumProfile
chrome_driver_path = src/capture/chromedriver.exe

[tshark]

tshark_interface = Ethernet
tshark_path = D:/software/Wireshark/tshark.exe

[mitmdump]

mitmdump_path = D:/software/Python/Scripts/mitmdump.exe

[path]

pcap_path = data/traffic/
responsebody_path = data/responsebody/
url_list_path = data/url/
url_class_path = data/url/url_class.csv
errorlog = data/errorlog.txt

[parameter]

time_duration = 120
chose_resolution = 720p