[mode]

if_use_url_list = 1
if_by_response = 1

[tshark]

tshark_path = D:/software/Wireshark/tshark.exe

[path]

pcap_path = data/traffic/
responsebody_path = data/responsebody/
url_list_path = data/url/
videofile_path = data/videofile/
fingerprint_path = data/fingerprint/
errorlog = data/errorlog.txt

[parameter]

video_mp4_itag = 136,398
video_webm_itag = 247
audio_mp4_itag = 
audio_webm_itag = 251
